<a href="https://colab.research.google.com/github/Antony-6487/basic-calc/blob/main/DSAIL_recruitment_questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
print('  /  |')
print(' /   |')
print('/___ |')

  /  |
 /   |
/___ |


making a basic calculator

In [9]:
num1=float(input('enter the first number:'))
op=input('enter the operator:')
num2=float(input('enter the second number:'))
if op=="+":
    print(num1 + num2)
elif op=="-":
    print(num1-num2)
elif op==('/'):
    print(num1/num2)
elif op=="*":
    print(num1 * num2)
else:
  print('invalid operator')


enter the first number:67
enter the operator:()
enter the second number:23
invalid operator


dictionaries

In [12]:
calendardictionary={
    "Jan":"January",
    "Feb":"February",
    "Mar":"March",
    "Apr":"April",
    "May":"May",
    "Jun":"June",
    "Jul":"July",
    "Aug":"August",
    "Sept":"September",
    "Oct":"October",
    "Nov":"November",
    "Dec":"December"
}
print(calendardictionary["Aug"])
print(calendardictionary.get("LOve","Not a valid key"))

August
Not a valid key


 Consider the system of linear equations below
 x1 +2x2 +x3 = 8
 x2 +x3 = 5
 x1 +2x3 = 7
 Express these equations in matrix form and determine x1 x2 and x3 using python.

In [8]:
import numpy as np
from scipy import linalg
# x1 + 2x2 +x3= 8
# x2 +x3= 5
# x1 + 2x3 = 7
a=np.array([[1, 2, 1],[0, 1, 1],[1, 0, 2]])
print(a)
b=np.array([[8],[5],[7]])
print(b)
answer=linalg.solve(a,b)
print(answer)
# or with x values clearly indicated
print("x1=", round(answer[0, 0], 3),"x2=", round(answer[0, 0], 3),"x3=", round(answer[0, 0], 3))

[[1 2 1]
 [0 1 1]
 [1 0 2]]
[[8]
 [5]
 [7]]
[[1.]
 [2.]
 [3.]]
x1= 1.0 x2= 1.0 x3= 1.0
